import = [ 
    "~/.config/alacritty/themes/blood_moon.toml",
    "~/.config/alacritty/font_size.toml" 
]

[colors]
draw_bold_text_with_bright_colors = true

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "SemiBold"

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.85

